### ISSUE TITLE
Thank you 🎉

### ISSUE THREAD

**Issue by bartveneman** [squidfunk/talks#1]
I saw you mentioned Project Wallace in one of your slides. Thanks! I also noticed you mentioning that there's still lot of flaws in analyzing CSS statically and I must say that it's eye-opening to look at these slides. Is there a recording of this talk? I'd love to watch it and share it with the followers of Project Wallace.
Thanks again!

**Comment by squidfunk** [comment]
Hey Bart,

thanks for your words. Unfortunately there’s no recording and the talk was in German, so probably not of much use 😉 however, I’m planning to give this talk again within the next months and write up something for a blog article. It’s part of my research on CSS. I will post my progress on Twitter.

Project Wallace is really the best (and most beautiful) static analyser, I had to mention it.

**Comment by bartveneman** [comment]
😊

I'm Dutch, so my German isn't that bad 😝 (although not great either). Really looking forward to more details, I'll keep a close eye 😄
